### ISSUE TITLE
Installer searches for libclang.so, doesn't find libclang.so.1

### ISSUE THREAD

**Issue by jpivarski** [Yamakaky/rust-bindgen#391] opened 2016-09-15 23:07 UTC
The `clang-3.5` package for Ubuntu 14.04 doesn't make a `libclang.so` link. It would probably be easy to also check for `libclang.so.1` when failing to find `libclang.so`. The only work-around that I know of is to add a symlink by hand, which is not something I want to do in directories under `/usr`.

**Comment by KyleMayes** [comment] 2016-09-22 21:57
This is actually a `clang-sys` issue, not specific to this repository. It's a duplicate of https://github.com/KyleMayes/clang-sys/issues/31 and the solution to this problem is mentioned in the README.md (symlink `libclang.so.1` to `libclang.so`).

I decided that handling versioned `libclang` binaries probably wasn't worth the hassle. Plus, symlinking gives the user the ability to select which version to use if they have multiple available.

**Comment by michaelwu** [comment] 2016-09-23 00:06
The libclang.so symlink is typically made by the dev package. Make sure you have libclang-dev installed. There should be no need to make the symlink manually.

**Closed** 2016-09-23 05:26 UTC
Labels: clang_sys

**Comment by jpivarski** [comment] 2016-09-23 22:31
Yes, you're right:

http://packages.ubuntu.com/search?searchon=contents&keywords=libclang.so&mode=filename&suite=trusty&arch=any

```
File	                            Packages
/usr/lib/llvm-3.3/lib/libclang.so	libclang-3.3-dev [not arm64]
/usr/lib/llvm-3.3/lib/libclang.so.1	libclang1-3.3 [not arm64]
/usr/lib/llvm-3.4/lib/libclang.so	libclang-3.4-dev
/usr/lib/llvm-3.4/lib/libclang.so.1	libclang1-3.4
/usr/lib/llvm-3.5/lib/libclang.so	libclang-3.5-dev
/usr/lib/llvm-3.5/lib/libclang.so.1	libclang1-3.5
```

Could this be added in parentheses next to Requirements: Clang >= 3.5 in README.md?
